controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Article;
use app\models\ArticleForm;
use app\models\Comment;
use app\models\CommentForm;
use yii\data\Pagination;
use yii\data\ActiveDataProvider;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                        [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        // Регистрируем модель формы статей и пробуем заполнить её данными
        // В случае успеха данные валидируем, сохраняем и обновляем страницу
        $model = new ArticleForm();
        if ($model->load(Yii::$app->request->post()) && $model->addArticle()) {
            return $this->refresh();
        }

        // Находим ТОП-5 комментируемых статей
        $queryMostPopular = Article::find()
                ->select([
                    '{{articles}}.*',
                ])
                ->joinWith('author')
                ->joinWith('comments')
                ->groupBy('{{articles}}.article_id')
                ->orderBy('COUNT({{comments}}.article_id) desc')
                ->limit(5)
                ->all();

        // Находим все остальные статьи в порядке даты добавления (включая ТОП-5)
        $query = Article::find()
                ->select([
                    '{{articles}}.*',
                    'COUNT({{comments}}.article_id)'
                ])
                ->joinWith('author')
                ->joinWith('comments')
                ->groupBy('{{articles}}.article_id');

        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC,
                ]
            ],
        ]);
        $posts = $provider->getModels();
        $pagination = $provider->getPagination();

        return $this->render('index', compact('posts', 'pagination', 'model', 'queryMostPopular'));
    }
    
    

    public function actionGetArticle() {
        $id = Yii::$app->getRequest()->getQueryParam('id');
        // Регистрируем сценарий ответов в модели и пробуем заполнить полученными данными
        // В случае успеха данные валидируем, сохраняем и обновляем страницу
        $model = new CommentForm(['scenario' => CommentForm::SCENARIO_REPLY]);
        if ($model->load(Yii::$app->request->post()) && $model->addComment($id)) {
            return $this->refresh();
        }
        // Регистрируем сценарий комментариев в модели и пробуем заполнить полученными данными
        // В случае успеха данные валидируем, сохраняем и обновляем страницу
        $model = new CommentForm(['scenario' => CommentForm::SCENARIO_COMMENT]);
        if ($model->load(Yii::$app->request->post()) && $model->addComment($id)) {
            return $this->refresh();
        }

        // Выборка статей со связью авторов (кто написал)
        $article = Article::find()
                ->joinWith('author')
                ->where(['articles.article_id' => $id])
                ->one();
        // Выборка комментариев со связью авторов (кто оставил)
        $comments = Comment::find()
                ->joinWith('author')
                ->where(['comments.article_id' => $id])
                ->andWhere('{{comments}}.reply_to_comment_id IS NULL');
        // Выборка ответов на комментарии со связью авторов (кто оставил)
        $replies = Comment::find()
                ->joinWith('author')
                ->where(['comments.article_id' => $id])
                ->andWhere('{{comments}}.reply_to_comment_id IS NOT NULL')
                ->indexBy('reply_to_comment_id')
                ->all();


        $provider = new ActiveDataProvider([
            'query' => $comments,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC,
                ]
            ],
        ]);
        $comments = $provider->getModels();
        $pagination = $provider->getPagination();

        return $this->render('article', compact('article', 'model', 'comments', 'pagination', 'replies'));
    }

}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/article.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\LinkPager;

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>    
            <?php
            echo html::encode($article->article_title);
            ?>
        </h1>
    </div>

    <div class="body-content">
        <div class="row">
            <?php
            echo "<p>" . html::encode($article->article_text) . "</p>";
            echo "<p><b>Добавлено:</b> " . html::encode($article->created_at) . "</p>";
            echo "<p><b>Автор:</b> " . html::encode($article->author['author_name']) . "</p>";
            echo "<hr><br>";

            echo "<h4>Комментарии читателей: </h4> <br>";

            foreach ($comments as $comment) {
                echo "<div style='border-bottom: 1px dashed black; border-right:1px solid black; margin:2%;'>";
                echo "<p><i>Автор:</i> " . html::encode($comment->author->author_name) . "</p>";
                echo "<p>" . html::encode($comment->comment_text) . "</p>";
                echo "<p><i>Добавлено: </i>" . html::encode($comment->created_at) . "</p><br>";
                
                // ищем ответы на комментарий
                if(array_key_exists($comment->comment_id, $replies)){
                       echo "<div style='margin-left: 5%;'>";
                        echo "<i>Ответил:</i> " . html::encode($replies[$comment->comment_id]->author->author_name) . "<br>";
                        echo html::encode($replies[$comment->comment_id]->comment_text);
                        echo "<br>";
                        echo "<i>Когда: </i>" . html::encode($replies[$comment->comment_id]->created_at);
                        echo "</div>";
                        echo "</div>";
                        continue;
                }
                // если не нашли, отображаем форму ответа для комментария
                if ($comment->reply_to_comment_id === NULL) {
                    $form = ActiveForm::begin(['id' => 'reply-form', 'options' => ['style' => 'width: 90%;
                                            font-size: 10px;
                    ']]);
                    echo $form->field($model, 'author')->textInput(['autofocus' => false]);
                    echo $form->field($model, 'text')->textarea(['rows' => 2]);
                    echo $form->field($model, 'reply_to')->hiddenInput(['value' => html::encode($comment->comment_id)])->label(false);
                    ?>

                    <div class="form-group">
                    <?= Html::submitButton('Прокомментировать', ['class' => 'btn btn-primary', 'name' => 'reply-button']) ?>
                    </div>

                    <?php
                    $form->errorSummary($model);
                    ActiveForm::end();
                }

                echo "</div>";
            }

            echo LinkPager::widget([
                'pagination' => $pagination,
            ]);
            ?>

        </div>


        <div style="margin:5%; ">

            <h3>Добавьте свой комментарий к статье</h3>
            <?php $form = ActiveForm::begin(['id' => 'comment-form']); ?>

            <?= $form->field($model, 'author')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>



            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'comment-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>

    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1><a href='https://docs.google.com/document/d/17PDF2B58dDnyj_d8xqtR_FskBLB1bnQOQDVBqW9g-FA/edit'>ТЗ</a></h1>

    </div>

    <div class="body-content">


            <?php
            echo "<h3 style='text-align:center;'>ТОП-5 комментируемых статей: </h3> <hr> <div class='owl-carousel'>";
            foreach($queryMostPopular as $popularPost){
                echo ""; 
                echo "<div><p style='
                    font-size: 10px;
                    font-style: italic;
                    font-weight: bold;'
                    >Добавлено: " .
                html::encode($popularPost->created_at) . "</p>";
                echo "<h3><a href='".Url::to(['site/get-article', 'id' => html::encode($popularPost->article_id)])."'>" . html::encode($popularPost->article_title) . "</a></h3>";

                echo "<br><p>" . mb_substr(html::encode($popularPost->article_text), 0, 100) . "..</p>";
                echo "<p>Автор: " . html::encode($popularPost->author['author_name']) . "</p>";
                echo "<p>Комментариев: ".html::encode(count($popularPost->comments)) . "</p></div>";
            }
            echo "</div><hr><h3 style='text-align:center;'>Все статьи: </h3>";
            foreach ($posts as $post) {
                echo "<hr>";
                echo "<p style='float: right; float: right;
                    font-size: 10px;
                    font-style: italic;
                    font-weight: bold;'
                    >Добавлено: " .
                $post->created_at . "</p>";
                echo "<h3><a href='".Url::to(['site/get-article', 'id' => html::encode($post->article_id)])."'>" . html::encode($post->article_title) . "</a></h3>";

                echo "<br><p>" . mb_substr(html::encode($post->article_text), 0, 100) . "..</p>";
                echo "<p>Автор: " . html::encode($post->author['author_name']) . "</p>";
                echo "<p>Комментариев: ".html::encode(count($post->comments)) . "</p>";
            }

            echo LinkPager::widget([
                'pagination' => $pagination,
            ]);
            ?>


        <hr>

        <h3>Опубликуйте свои мысли</h3>
<?php $form = ActiveForm::begin(['id' => 'article-form']); ?>

        <?= $form->field($model, 'author')->textInput(['autofocus' => false]) ?>

        <?= $form->field($model, 'title') ?>

        <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>



        <div class="form-group">
<?= Html::submitButton('Добавить', ['class' => 'btn btn-primary', 'name' => 'article-button']) ?>
        </div>

<?php ActiveForm::end(); ?>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>